version: '3'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    #image: bot
    depends_on:
      - database
    networks:
      - bot-db
    restart: always

  database:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - bot-db
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
networks:
  bot-db: 
  #mongo-express:
      #image: mongo-express
      #restart: always
      #ports:
        #- 8081:8081
      #environment:
        #ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        #ME_CONFIG_MONGODB_ADMINPASSWORD: admin
        #ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/        
